### PR TITLE
Add Dockerfile and docker build action

### PR DESCRIPTION
**Pull request by Jasper-Ben**
Add Dockerfile. Also, build, tag and push docker image on push

### CODE REVIEW

**Comment by Jasper-Ben** [comment]
Delivering todocheck as container image makes the integration into CI systems easier

**Comment by Jasper-Ben** [comment]
Also relates to https://github.com/preslavmihaylov/todocheck/issues/83

**Comment by preslavmihaylov** [comment]
@Jasper-Ben I'm not sure this is going to work.

When I copied your `Dockerfile` locally, I did:
```
docker build . -t todocheck:test
```

Afterwards, I created a folder with `main.go`:
```
package main

import "fmt"

// TODO: invalid
func main() {
	fmt.Println("hello world")
}
```

And a `.todocheck.yaml` config:
```
origin: github.com/user/repository
issue_tracker: GITHUB
```

After I run:
```
docker run -it todocheck:test
```

I get the following error:
```
2022/09/11 07:01:10 couldn't open configuration file: file ./.todocheck.yaml not found: unable to automatically detect issue tracker: open ./.git/config: no such file or directory
```

I believe this is because todocheck is running in the context of its container, rather than my local file system.
Could you explain how this is supposed to work in CI or when used locally?

**Comment by Jasper-Ben** [comment]
Hi!
Yes, you guessed the reason correctly. I should include more detail in the README file. The most straight forward way for mounting the project's directory into the container. Additionally, you would have to parse the tracker auth token into the container. When running it locally, this could look like this:

```bash
docker run -it -v /path/to/project/on/host:/project -e TODOCHECK_AUTH_TOKEN=<token>  todocheck:test --basepath /project
```

I will add this to the README.

**Comment by Jasper-Ben** [comment]
Also another thing I noticed is that you add some versioning during the build of todocheck: https://github.com/preslavmihaylov/todocheck/blob/master/Makefile#L5

This currently is not the case with the docker build. I don't think it is a huge deal, since the docker tag itself can be used to identify the version, but if you say that needs to be amended, I could take a look into it.

**Comment by preslavmihaylov** [comment]
I think a more sensible approach would be to configure the docker image build to be done on new releases & it should match the version of the release.

**Comment by Jasper-Ben** [comment]
> I think a more sensible approach would be to configure the docker image build to be done on new releases & it should match the version of the release.

This (and more) is basically what the GitHub action will do. If you tag and push a git commit, the GitHub action will automatically build and tag the docker image appropriately. Optionally, but from experience recommended (minimum: at least for the master branch), It also builds and pushes an appropriately tagged docker image for a push to any branch, keeping the latest (head of branch). This is useful if a certain feature is required but hasn't been merged or released yet. The user of the software therefore could opt to use the image for the latest master branch commit until the next release is available.

**Comment by preslavmihaylov** [comment]
I'll make a todocheck fork & play around with this to validate that it works correctly

**Comment by preslavmihaylov** [comment]
Hey @Jasper-Ben I managed to play around with this in a fork & set it up nicely.

Check out https://github.com/preslavmihaylov/todocheck/pull/200

Via those changes:
 * docker image is built on push to master only + new releases
 * Running `todocheck --version` now corresponds to the git sha (if built via master) or the version (if via release)

Would you like to replicate those changes in this PR so that I can merge it? I could just merge that one, but I don't want to steal the credits :)

**Comment by Jasper-Ben** [comment]
> Would you like to replicate those changes in this PR so that I can merge it?

Done :)

I've done some further cleanup to the Dockerfile (removed unnecessary `cp` and now unused make package), squashed and pushed. Please verify :)

**Review by preslavmihaylov — APPROVED** [review]
Thanks for the contribution!

**Pull request merged**
