### PR TITLE
Added unit tests for fetcher, checker and matchers packages

### LINKED ISSUE #173: Increase unit test coverage
In order to submit this project for some of the curated go projects, we'll need to ensure a decent code coverage report. Currently, we don't have one since our integration tests are setup in a way that they test the application as a blackbox, which prevents us from having code coverage.

I'll welcome any PR which adds a new unit test & increases the code coverage.

### PR DESCRIPTION
**Pull request by eisandbar**
As issue #173 is pretty broad I decided to first work on part of it.

Did slight refactoring in fetcher.go for easier testing and added tests for all possible errors in Fetch()

Checker now accepts interface of type Fetcher for easier mocking. Added tests for all possible errors in Check()

Added tests for all 3 functions in matchers.go. Tests use supportedMatchers for test cases so updating supportedMatchers should update tests. 

go test -cover now shows 100% for these 3 files

### CODE REVIEW

**Review by preslavmihaylov — APPROVED** [review]
Nice, thanks for the contribution!

I've removed the "closes" tag in the description as it partially completes that issue.

**Comment by preslavmihaylov** [comment]
@eisandbar looks like there are some lint issues. Could you check em out. After that, we're good to go

**Comment by eisandbar** [comment]
> @eisandbar looks like there are some lint issues. Could you check em out. After that, we're good to go

Hi! I fixed the lint errors and running golangci-lint v1.48.0 on my computer shows no errors, but the lint action still fails on the same files.

**Comment by preslavmihaylov** [comment]
@eisandbar could you rebase? The lint issue should be resolved now

**Comment by eisandbar** [comment]
@preslavmihaylov  Yes, no problem

**Review by preslavmihaylov — APPROVED** [review]

**Pull request merged**
