### PR TITLE
Env var overrides cached token

### LINKED ISSUE #175: auth tokens cache overrides auth token specified via env variable
Whenever you specify an auth token for e.g. domain `hello.myjira.net` with auth token via env variable:
```
$ TODOCHECK_AUTH_TOKEN=<auth-token> ./todocheck
```

if there is an auth token already present for that domain in `~/.todocheck/authtokens.yaml`, todocheck will use the auth token from that file vs. using the one specified via the env variable.

This shouldn't happen. The env variable should override the auth tokens cache.

### PR DESCRIPTION
**Pull request by aaronangxz**
Fixes #175

### CODE REVIEW

**Comment by aaronangxz** [comment]
@preslavmihaylov I'm trying to run unit test `TestAuthTokensCache` however i'm getting

`program exited with an unexpected exit code: fork/exec ../todocheck: no such file or directory`
and debugging shows `"couldn't teardown test environment: failed to delete tokens cache ./...`

Do you mind explaining what is wrong here? Do I need to do anything to set up test env? thanks!

**Comment by preslavmihaylov** [comment]
You need to first build the `todocheck` binary to run the tests.

If you run `make test` instead of manual `go test ...` it should work.

**Comment by aaronangxz** [comment]
@preslavmihaylov Great, I managed to run the tests now! However, I might be overlooking some stuff here, you can let me know if the unit test is not sufficient

**Review by preslavmihaylov — APPROVED** [review]
Awesome!

Thanks for the contribution

**Comment by preslavmihaylov** [comment]
Since it's WIP, I won't merge it yet. Let me know if you're finished

**Comment by aaronangxz** [comment]
Marked as ready, thanks! @preslavmihaylov

**Pull request merged**
